#!/usr/bin/env python3
"""
Generate embedded brand assets from assets/brand_source.png:

  - SPI TFT: 80x80 RGB565 (full colour, cropped subject).
  - I2C mono OLED: 64x64 1-bpp row-major MSB-first (Floyd–Steinberg dither),
    separate look optimised for SSD1306/SH1106.

Usage:
  python tools/gen_brand_turnip.py [input.png] [output.c]

Default output: tools/probe_marker_regen_snippet.c — paste the two static arrays into
main/panel_probes.c (replace k_probe_marker_turnip_rgb565 / k_probe_marker_turnip_mono).
"""
from __future__ import annotations

import pathlib
import sys

try:
    from PIL import Image
except ImportError as e:
    raise SystemExit("Install Pillow: pip install Pillow") from e

ROOT = pathlib.Path(__file__).resolve().parents[1]

RGB_W = RGB_H = 80
MONO_W = MONO_H = 64


def rgb888_to_rgb565(r: int, g: int, b: int) -> int:
    r5 = (r * 31 + 127) // 255
    g6 = (g * 63 + 127) // 255
    b5 = (b * 31 + 127) // 255
    return (r5 << 11) | (g6 << 5) | b5


def crop_subject_rgb(im: Image.Image) -> Image.Image:
    """Tight crop on non–near-white pixels (same logic as before)."""
    px = im.load()
    w, h = im.size
    bg_thresh = 248
    min_x, min_y = w, h
    max_x, max_y = 0, 0
    for y in range(h):
        for x in range(w):
            r, g, b = px[x, y]
            if r < bg_thresh or g < bg_thresh or b < bg_thresh:
                min_x = min(min_x, x)
                min_y = min(min_y, y)
                max_x = max(max_x, x)
                max_y = max(max_y, y)
    if max_x < min_x:
        raise SystemExit("No non-white content found in image")
    pad = 4
    min_x = max(0, min_x - pad)
    min_y = max(0, min_y - pad)
    max_x = min(w - 1, max_x + pad)
    max_y = min(h - 1, max_y + pad)
    return im.crop((min_x, min_y, max_x + 1, max_y + 1))


def pack_ssd1306_page_order(im_bw: Image.Image) -> list[int]:
    """
    SSD1306 / SH1106 framebuffer: for each page (block of 8 rows), for each column x,
    one byte — bit k is pixel (x, page*8+k), k=0 top of page. Matches esp_lcd SSD1306 draw_bitmap.
    """
    w, h = im_bw.size
    if h % 8 != 0:
        raise SystemExit("Mono height must be multiple of 8")
    px = im_bw.load()
    out: list[int] = []
    for page in range(h // 8):
        for x in range(w):
            byte = 0
            for bit in range(8):
                y = page * 8 + bit
                if px[x, y] > 0:
                    byte |= 1 << bit
            out.append(byte)
    return out


def emit_uint16_array(name: str, pixels: list[int], lines: list[str]) -> None:
    lines.append(f"static const uint16_t {name}[{len(pixels)}] = {{")
    row: list[str] = []
    for i, p in enumerate(pixels):
        row.append(f"0x{p:04X}u")
        if len(row) >= 10:
            lines.append("    " + ", ".join(row) + ",")
            row = []
    if row:
        lines.append("    " + ", ".join(row) + ",")
    lines.append("};")
    lines.append("")


def emit_uint8_array(name: str, data: list[int], lines: list[str]) -> None:
    lines.append(f"static const uint8_t {name}[{len(data)}] = {{")
    row: list[str] = []
    for i, b in enumerate(data):
        row.append(f"0x{b:02X}u")
        if len(row) >= 16:
            lines.append("    " + ", ".join(row) + ",")
            row = []
    if row:
        lines.append("    " + ", ".join(row) + ",")
    lines.append("};")
    lines.append("")


def main() -> None:
    default_in = ROOT / "assets" / "brand_source.png"
    in_path = pathlib.Path(sys.argv[1]) if len(sys.argv) > 1 else default_in
    out_path = pathlib.Path(sys.argv[2]) if len(sys.argv) > 2 else ROOT / "tools" / "probe_marker_regen_snippet.c"

    if not in_path.is_file():
        raise SystemExit(f"Input not found: {in_path}")

    im = Image.open(in_path).convert("RGB")
    cropped = crop_subject_rgb(im)

    # --- SPI: 80x80 RGB565 ---
    rgb_small = cropped.resize((RGB_W, RGB_H), Image.Resampling.LANCZOS)
    px = rgb_small.load()
    rgb565: list[int] = []
    for y in range(RGB_H):
        for x in range(RGB_W):
            r, g, b = px[x, y]
            rgb565.append(rgb888_to_rgb565(r, g, b))

    # --- I2C mono: 64x64 dithered 1-bpp (separate visual from raw downscale) ---
    gray = cropped.resize((MONO_W, MONO_H), Image.Resampling.LANCZOS).convert("L")
    # Slight contrast lift helps root silhouette on OLED
    gray = Image.eval(gray, lambda p: min(255, max(0, int((p - 8) * 1.08))))
    mono_bw = gray.convert("1", dither=Image.Dither.FLOYDSTEINBERG)
    mono_bytes = pack_ssd1306_page_order(mono_bw)

    lines = [
        "/* Generated by tools/gen_brand_turnip.py — paste into main/panel_probes.c */",
        "",
        f"/* SPI: {RGB_W}x{RGB_H} RGB565, {len(rgb565) * 2} bytes */",
    ]
    emit_uint16_array("k_probe_marker_turnip_rgb565", rgb565, lines)
    lines.append(f"/* I2C mono: {MONO_W}x{MONO_H} 1bpp, {len(mono_bytes)} bytes (dithered) */")
    emit_uint8_array("k_probe_marker_turnip_mono", mono_bytes, lines)

    out_path.write_text("\n".join(lines), encoding="utf-8")
    print(
        f"Wrote {out_path}\n"
        f"  RGB565 {RGB_W}x{RGB_H} = {len(rgb565) * 2} bytes\n"
        f"  mono   {MONO_W}x{MONO_H} = {len(mono_bytes)} bytes"
    )


if __name__ == "__main__":
    main()
